basster_legacy_bridge:
    # change path to the folder containing your legacy .php scripts.
    legacy_path:    '%kernel.root_dir%'
    # optional prepend script (see http://php.net/manual/en/ini.core.php#ini.auto-prepend-file)
    # prepend_script: '/full/path/to/my/legacy/autoPrependFile.php' # can be ommited
    # optional append script (see http://php.net/manual/en/ini.core.php#ini.auto-append-file)
    # append_script:  '/full/path/to/my/legacy/autoAppendFile.php' # can be ommited
